<h1>Важность признаков - Decision Tree Classifier</h1>

In [1]:
import pandas as pd
import numpy as np
from sklearn import tree

In [2]:
path_to_data = 'D:\\WORK\ml\\data\\'

In [3]:
data = pd.read_csv(path_to_data+'titanic_dataset2.csv', index_col='PassengerId')

In [4]:
features = data.loc[:,['Survived', 'Pclass', 'Fare', 'Age', 'Sex']]

In [5]:
features_flt = features.dropna(how='any', axis=0)
# features_flt = features[flt == False]
tgt_var = features_flt['Survived']
features_flt = features_flt.drop('Survived', 1)
features_flt['Sex'] = features_flt['Sex'].map(lambda s: s == 'female'); features_flt

             Pclass      Fare   Age    Sex
PassengerId
1                 3    7.2500  22.0  False
2                 1   71.2833  38.0   True
3                 3    7.9250  26.0   True
4                 1   53.1000  35.0   True
5                 3    8.0500  35.0  False
7                 1   51.8625  54.0  False
8                 3   21.0750   2.0  False
9                 3   11.1333  27.0   True
10                2   30.0708  14.0   True
11                3   16.7000   4.0   True
12                1   26.5500  58.0   True
13                3    8.0500  20.0  False
14                3   31.2750  39.0  False
15                3    7.8542  14.0   True
16                2   16.0000  55.0   True
17                3   29.1250   2.0  False
19                3   18.0000  31.0   True
21                2   26.0000  35.0  False
22                2   13.0000  34.0  False
23                3    8.0292  15.0   True
24                1   35.5000  28.0  False
25                3   21.0750   8.0   True
26                3   31.3875  38.0   True
28                1  263.0000  19.0  False
31                1   27.7208  40.0  False
34                2   10.5000  66.0  False
35                1   82.1708  28.0  False
36                1   52.0000  42.0  False
38                3    8.0500  21.0  False
39                3   18.0000  18.0   True
...             ...       ...   ...    ...
857               1  164.8667  45.0   True
858               1   26.5500  51.0  False
859               3   19.2583  24.0   True
861               3   14.1083  41.0  False
862               2   11.5000  21.0  False
863               1   25.9292  48.0   True
865               2   13.0000  24.0  False
866               2   13.0000  42.0   True
867               2   13.8583  27.0   True
868               1   50.4958  31.0  False
870               3   11.1333   4.0  False
871               3    7.8958  26.0  False
872               1   52.5542  47.0   True
873               1    5.0000  33.0  False
874               3    9.0000  47.0  False
875               2   24.0000  28.0   True
876               3    7.2250  15.0   True
877               3    9.8458  20.0  False
878               3    7.8958  19.0  False
880               1   83.1583  56.0   True
881               2   26.0000  25.0   True
882               3    7.8958  33.0  False
883               3   10.5167  22.0   True
884               2   10.5000  28.0  False
885               3    7.0500  25.0  False
886               3   29.1250  39.0   True
887               2   13.0000  27.0  False
888               1   30.0000  19.0   True
890               1   30.0000  26.0  False
891               3    7.7500  32.0  False

[714 rows x 4 columns]

In [6]:
clf = tree.DecisionTreeClassifier(random_state=241)
for f, i in zip(features_flt.columns, 
                clf.fit(features_flt, tgt_var).feature_importances_):
    print(f"{f}: {i}")

Pclass: 0.14751816099515025
Fare: 0.2953846784065746
Age: 0.25658494964003575
Sex: 0.3005122109582393